[package]
name = "url-dispatch"
version = "0.1.0"
authors = ["wuyuz <wang@ik.conm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
actix-web = "3"
futures = "0.3.1"
openssl = "0.10"
serde = "1.0"